version: '3.8'

services:
 notes:
  build:
   context: .
  ports:
   - 5000:5000
   - 9229:9229
  environment:
   - SERVER_PORT=5000
   - MONGODB_URL="mongodb+srv://group18:eliceswengineer@mycluster.0cia7.mongodb.net/?retryWrites=true&w=majority"

  volumes:
   - ./:/app
  command: npm run debug